Feature/18
jakpolak/find-your-course-common pull request #5
Opened 2021-09-08 10:29 UTC by quebonafide

interface refactor

2021-09-12 13:42 UTC, jakpolak requested changes
Great job! However, there are a few small issues to fix.

2021-09-12 13:42 UTC, jakpolak commented on src/types/courses/sendCoursePayload.ts
> +export interface SendCoursePayload {
It may be a good idea to rename this to `CoursePayload` cause all other interfaces are extending this one.

2021-09-12 13:42 UTC, jakpolak commented on src/types/courses/addCoursePayload.ts
> +export interface AddCoursePayload extends SendCoursePayload {
![Screenshot 2021-09-12 at 15 16 17](https://user-images.githubusercontent.com/25429599/132989022-a322e999-8569-499f-829a-a04e6bfdb90a.png)
This type is used only in `courses/src/controllers/get-all-courses.ts` and to extends others, so the name is not accurate.
There are two ways to improve it: 
1. Rename the interface
2. Move both properties to `CoursePayload` and make them optional `?` then this type is not required (all other types will extend the `CoursePayload`)

IMO. the second option seems to be better

2021-09-12 13:42 UTC, jakpolak commented on src/types/courses/createdCoursePayload.ts
> +export interface CreatedCoursePayload extends AddCoursePayload {
Consider renaming it to `CourseResponsePayload` cause it's used mostly on the frontend to display data + returned type on update.

2021-09-13 10:31 UTC, quebonafide commented on src/types/courses/addCoursePayload.ts
> +export interface AddCoursePayload extends SendCoursePayload {
resolved by implementing the second option

2021-09-13 10:32 UTC, quebonafide commented on src/types/courses/createdCoursePayload.ts
> +export interface CreatedCoursePayload extends AddCoursePayload {
considered and done

2021-09-13 10:32 UTC, quebonafide commented on src/types/courses/sendCoursePayload.ts
> +export interface SendCoursePayload {
it indeed was a good idea

2021-09-13 11:00 UTC, jakpolak approved these changes

2021-09-13 11:40 UTC, merged